#!/usr/bin/env python3
"""
Writes backend/parkingcore/local_settings.py on the CI runner from GitHub
Secrets, so the FTP deploy ships it like any other file.

Why this exists: SamKirkland/FTP-Deploy-Action mirrors the checkout against
.ftp-deploy-sync-state.json on the server, so anything gitignored looks
"deleted" and gets removed from prod. Generating the file here means it is
always present at deploy time, while the real credentials live only in
GitHub Secrets -- never in the repo.

Run by the "Generate production settings" step in ../workflows/parking.yml.
"""
import os
import sys

OUT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "backend", "parkingcore", "local_settings.py",
)

# Secrets that must exist -- deploying without any of these would either break
# the app or silently fall back to a dev value, so fail the build instead.
REQUIRED = [
    "DB_NAME", "DB_USER", "DB_PASSWORD", "DB_HOST",
    "DJANGO_SECRET_KEY", "RESTART_TOKEN",
]

# Optional; omitted from the generated file when unset, leaving settings.py's
# default in place.
OPTIONAL = [
    "DB_PORT", "EMAIL_HOST_PASSWORD", "PARKING_WEBHOOK_SECRET",
    "EASYMANAGE_INTEGRATION_API_KEY", "EASYMANAGE_API_BASE_URL",
    "PARKING_READ_API_KEY", "DEV_SYNC_TOKEN",
]


def main():
    missing = [k for k in REQUIRED if not os.environ.get(k)]
    if missing:
        sys.exit(
            "Missing required GitHub Secret(s): %s\n"
            "Add them under Settings -> Secrets and variables -> Actions, "
            "then re-run this workflow." % ", ".join(missing)
        )

    env = {k: os.environ[k] for k in REQUIRED}
    env.update({k: os.environ[k] for k in OPTIONAL if os.environ.get(k)})

    allowed_host = os.environ.get("ALLOWED_HOST", "").strip()
    allowed_hosts = [allowed_host] if allowed_host else []

    lines = [
        "# GENERATED BY CI -- DO NOT EDIT THIS FILE ON THE SERVER.",
        "# Every deploy overwrites it. Change the values in GitHub Secrets:",
        "# Settings -> Secrets and variables -> Actions.",
        "# Source: .github/scripts/gen_local_settings.py",
        "",
        "DEBUG = False",
        "ENVIRONMENT = 'production'",
        "ALLOWED_HOSTS = %r" % (allowed_hosts,),
        "",
        "SECRET_KEY = %r" % env["DJANGO_SECRET_KEY"],
        "",
        "DATABASES = {",
        "    'default': {",
        "        'ENGINE': 'django.db.backends.postgresql',",
        "        'NAME': %r," % env["DB_NAME"],
        "        'USER': %r," % env["DB_USER"],
        "        'PASSWORD': %r," % env["DB_PASSWORD"],
        "        'HOST': %r," % env["DB_HOST"],
        "        'PORT': %r," % env.get("DB_PORT", "5432"),
        "    }",
        "}",
        "",
    ]

    # settings.py reads these off the module, so a plain assignment is enough.
    for key, setting in [
        ("RESTART_TOKEN", "RESTART_TOKEN"),
        ("DEV_SYNC_TOKEN", "DEV_SYNC_TOKEN"),
        ("EMAIL_HOST_PASSWORD", "EMAIL_HOST_PASSWORD"),
        ("PARKING_WEBHOOK_SECRET", "PARKING_WEBHOOK_SECRET"),
        ("EASYMANAGE_INTEGRATION_API_KEY", "EASYMANAGE_INTEGRATION_API_KEY"),
        ("EASYMANAGE_API_BASE_URL", "EASYMANAGE_API_BASE_URL"),
        ("PARKING_READ_API_KEY", "PARKING_READ_API_KEY"),
    ]:
        if key in env:
            lines.append("%s = %r" % (setting, env[key]))

    lines.append("")
    with open(OUT, "w") as fh:
        fh.write("\n".join(lines))

    # Names only -- never echo the values into the build log.
    print("Wrote %s with: %s" % (OUT, ", ".join(sorted(env))))


if __name__ == "__main__":
    main()
