# Generated by Django 5.2.2 on 2025-06-07 10:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouponBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('validation_type', models.CharField(choices=[('FREE_MINUTES', 'Grant Free Minutes'), ('COMPLETE_WAIVER', 'Waive Entire Session')], max_length=20)),
                ('value_minutes', models.PositiveIntegerField(default=0, help_text="For 'Grant Free Minutes' coupons.")),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('number_of_coupons', models.PositiveIntegerField(default=10)),
                ('base_price_per_coupon', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this batch purchase.')),
            ],
            options={
                'verbose_name': 'Coupon Batch Purchase',
                'verbose_name_plural': 'Coupon Batch Purchases',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='ParkingConfiguration',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('currency_symbol', models.CharField(default='NRs', max_length=5)),
                ('company_name', models.CharField(blank=True, default='Django Parking Inc.', max_length=100)),
            ],
            options={
                'verbose_name': 'Parking System Configuration',
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('plan_type', models.CharField(choices=[('HOURLY', 'Hourly Rate'), ('FLAT_RATE_PER_DAY', 'Flat Rate Per Day'), ('TIERED_HOURLY', 'Tiered Hourly Blocks')], default='HOURLY', max_length=20)),
                ('rate_details', models.JSONField(default=dict)),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The minimum fee for this plan, if the calculated charge is > 0. Set to 0 for no minimum.', max_digits=6)),
            ],
            options={
                'verbose_name': 'Pricing Plan',
                'verbose_name_plural': 'Pricing Plans',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('license_plate', models.CharField(db_index=True, max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendor / Tenant',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('validation_type', models.CharField(choices=[('FREE_MINUTES', 'Grant Free Minutes'), ('COMPLETE_WAIVER', 'Waive Entire Session')], max_length=20)),
                ('value_minutes', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('times_used', models.PositiveIntegerField(default=0, editable=False)),
                ('batch', models.ForeignKey(blank=True, help_text='The batch this coupon was generated from, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='management.couponbatch')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.vendor')),
            ],
            options={
                'verbose_name': 'Parking Coupon',
                'verbose_name_plural': 'Parking Coupons',
            },
        ),
        migrations.CreateModel(
            name='ParkingPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('price_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_passes', to='management.staff')),
            ],
            options={
                'verbose_name': 'Staff/Subscription Pass',
                'verbose_name_plural': 'Staff/Subscription Passes',
                'ordering': ['-valid_until'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('free_duration_minutes', models.PositiveIntegerField(default=5)),
                ('pricing_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.pricingplan')),
            ],
            options={
                'verbose_name': 'Vehicle Type',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.vehicletype'),
        ),
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('license_plate', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('calculated_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Credit/Debit Card'), ('ONLINE_QR', 'Online/QR Payment')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('PAID', 'Paid'), ('WAIVED', 'Waived'), ('COVERED_BY_PASS', 'Covered by Pass')], db_index=True, default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('applied_coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.coupon')),
                ('applied_pass', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.parkingpass')),
                ('registered_staff_member', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_sessions', to='management.staff')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.vehicletype')),
            ],
            options={
                'verbose_name': 'Parking Session',
                'ordering': ['-entry_time'],
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.vendor'),
        ),
        migrations.AddField(
            model_name='couponbatch',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_batches', to='management.vendor'),
        ),
    ]
