# Generated by Django 5.2.2 on 2025-06-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponbatch',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('ONLINE_PAYMENT', 'Online Payment')], max_length=20, null=True),
        ),
    ]
