# Generated by Django 5.2.2 on 2025-06-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_parkingsession_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkingpass',
            options={'ordering': ['-valid_until'], 'verbose_name': 'Subscription Pass', 'verbose_name_plural': 'Subscription Passes'},
        ),
    ]
