# Generated by Django 5.2.2 on 2026-07-20 08:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_staff_card_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='card_issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_card_active',
            field=models.BooleanField(default=True, help_text='Uncheck to instantly block this card at the gate (lost/leaked) without losing history.'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='card_code',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Encoded on the tenant's permanent physical parking card (QR/barcode). Never rotates — regenerate via admin action if the physical card is lost.", unique=True),
        ),
        migrations.CreateModel(
            name='CardScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code_used', models.CharField(blank=True, max_length=64)),
                ('action', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit'), ('REJECTED', 'Rejected')], max_length=10)),
                ('source', models.CharField(choices=[('PHYSICAL', 'Physical Card'), ('DIGITAL', 'Digital Card')], default='PHYSICAL', max_length=10)),
                ('reject_reason', models.CharField(blank=True, max_length=100)),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='management.staff')),
            ],
            options={
                'verbose_name': 'Card Scan Log',
                'verbose_name_plural': 'Card Scan Logs',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
