# Generated by Django 5.2.2 on 2026-07-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_staff_card_issued_at_staff_is_card_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardscanlog',
            name='source',
            field=models.CharField(choices=[('PHYSICAL', 'Physical Card'), ('DIGITAL', 'Digital Card (Online)'), ('OFFLINE', 'Digital Card (Offline)')], default='PHYSICAL', max_length=10),
        ),
    ]
