# Generated by Django 5.2.2 on 2026-07-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_cardscanlog_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardscanlog',
            name='is_sample',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this record was generated by seed_parking_data. Never set manually.'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_sample',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this record was generated by seed_parking_data. Never set manually.'),
        ),
        migrations.AddField(
            model_name='couponbatch',
            name='is_sample',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this record was generated by seed_parking_data. Never set manually.'),
        ),
        migrations.AddField(
            model_name='parkingpass',
            name='is_sample',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this record was generated by seed_parking_data. Never set manually.'),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='is_sample',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this record was generated by seed_parking_data. Never set manually.'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='is_sample',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this record was generated by seed_parking_data. Never set manually.'),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_sample',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this record was generated by seed_parking_data. Never set manually.'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='is_sample',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this record was generated by seed_parking_data. Never set manually.'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_sample',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this record was generated by seed_parking_data. Never set manually.'),
        ),
    ]
