# Generated by Django 5.2.2 on 2026-08-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_add_is_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('event_type', models.CharField(max_length=50)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=10)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Webhook Event Log',
                'verbose_name_plural': 'Webhook Event Logs',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='category',
            field=models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike')], default='CAR', max_length=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bike_quota',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='car_quota',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='external_tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='gate_access_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='sync_source',
            field=models.CharField(blank=True, choices=[('webhook', 'Webhook'), ('pull', 'Pull Reconcile'), ('manual', 'Manual')], max_length=20, null=True),
        ),
    ]
