# Generated by Django 5.2.2 on 2026-08-02 15:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_webhookeventlog_vehicletype_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='stamp_free_minutes',
            field=models.PositiveIntegerField(default=60, help_text="Free parking minutes granted each time this tenant stamps a visitor's ticket."),
        ),
        migrations.CreateModel(
            name='TicketStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_minutes_granted', models.PositiveIntegerField(help_text="Snapshot of the tenant's stamp_free_minutes at the time this stamp was recorded.")),
                ('stamped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_sample', models.BooleanField(db_index=True, default=False, help_text='True if this record was generated by seed_parking_data. Never set manually.')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamps', to='management.parkingsession')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_stamps', to='management.vendor')),
            ],
            options={
                'verbose_name': 'Ticket Stamp',
                'verbose_name_plural': 'Ticket Stamps',
                'ordering': ['-stamped_at'],
            },
        ),
    ]
