# Generated by Django 5.2.2 on 2026-08-03 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_vendor_stamp_free_minutes_ticketstamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsession',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('PAID', 'Paid'), ('WAIVED', 'Waived'), ('COVERED_BY_PASS', 'Covered by Pass'), ('STAMPED', 'Stamped')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='TenantBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overage_minutes', models.PositiveIntegerField(help_text="Minutes parked beyond the total free minutes granted by this ticket's stamps.")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_sample', models.BooleanField(db_index=True, default=False, help_text='True if this record was generated by seed_parking_data. Never set manually.')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_bill', to='management.parkingsession')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_bills', to='management.vendor')),
            ],
            options={
                'verbose_name': 'Tenant Bill',
                'verbose_name_plural': 'Tenant Bills',
                'ordering': ['-created_at'],
            },
        ),
    ]
