# Generated by Django 5.2.2 on 2026-08-19 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_alter_parkingsession_status_tenantbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingpass',
            name='extra_vehicles',
            field=models.ManyToManyField(blank=True, help_text='Other vehicles covered by this same pass, besides the primary staff member above. One price covers every vehicle listed — only one of them may be inside the lot at a time.', related_name='parking_passes_covered', to='management.staff'),
        ),
        migrations.AddField(
            model_name='parkingpass',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank transfer'), ('CHEQUE', 'Cheque'), ('SALARY_DEDUCTION', 'Salary deduction')], default='CASH', max_length=20),
        ),
        migrations.AddField(
            model_name='parkingpass',
            name='reminder_enabled',
            field=models.BooleanField(default=False, help_text='Send a renewal reminder 7 days before this pass ends.'),
        ),
        migrations.AlterField(
            model_name='parkingpass',
            name='staff',
            field=models.ForeignKey(help_text='Primary pass holder. Additional vehicles covered by the same pass go in extra_vehicles.', on_delete=django.db.models.deletion.CASCADE, related_name='parking_passes', to='management.staff'),
        ),
    ]
