# Generated by Django 5.2.2 on 2026-09-15 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_parkingpass_extra_vehicles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingconfiguration',
            name='tenant_window_enabled',
            field=models.BooleanField(default=False, help_text='When on, registered tenant vehicles are only free within the daily access window below; time outside it is billed normally.'),
        ),
        migrations.AddField(
            model_name='parkingconfiguration',
            name='tenant_window_end',
            field=models.TimeField(default=datetime.time(18, 45)),
        ),
        migrations.AddField(
            model_name='parkingconfiguration',
            name='tenant_window_start',
            field=models.TimeField(default=datetime.time(6, 0)),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tenant_window_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tenant_window_start',
            field=models.TimeField(blank=True, help_text='Overrides the global tenant access window for this tenant only. Leave both start and end blank to use the global default.', null=True),
        ),
    ]
