# Generated by Django 5.2.2 on 2026-09-24 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_parkingconfiguration_tenant_window_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='auto_closed',
            field=models.BooleanField(db_index=True, default=False, editable=False, help_text='Closed by a staff correction, not a real exit tap — exit_time is not when the car left. Excluded from every duration/usage/billing figure (ParkingSession.objects.valid()).'),
        ),
        migrations.AlterField(
            model_name='cardscanlog',
            name='action',
            field=models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit'), ('REJECTED', 'Rejected'), ('FORCED_ENTRY', 'Forced Entry (staff correction)')], max_length=12),
        ),
        migrations.AlterField(
            model_name='cardscanlog',
            name='source',
            field=models.CharField(choices=[('PHYSICAL', 'Physical Card'), ('DIGITAL', 'Digital Card (Online)'), ('OFFLINE', 'Digital Card (Offline)'), ('RFID', 'RFID Card')], default='PHYSICAL', max_length=10),
        ),
        migrations.CreateModel(
            name='RFIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, help_text='Digits the reader types when the card is tapped, e.g. 0012345678. Leading zeros matter — copy it exactly.', max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to block this card at the gate (lost/returned) without losing history.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_cards', to='management.staff', verbose_name='Tenant member')),
            ],
            options={
                'verbose_name': 'RFID Card',
                'verbose_name_plural': 'RFID Cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='rfid_card',
            field=models.ForeignKey(blank=True, editable=False, help_text='The RFID card tapped to open this session, if any.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='management.rfidcard'),
        ),
        migrations.AddConstraint(
            model_name='parkingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('exit_time__isnull', True)), fields=('rfid_card',), name='one_open_session_per_rfid_card'),
        ),
    ]
