# Generated by Django 5.2.2 on 2026-09-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_rfid_card_and_session_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingconfiguration',
            name='tenant_window_enabled',
        ),
        migrations.RemoveField(
            model_name='parkingconfiguration',
            name='tenant_window_end',
        ),
        migrations.RemoveField(
            model_name='parkingconfiguration',
            name='tenant_window_start',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='tenant_window_end',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='tenant_window_start',
        ),
        migrations.AddField(
            model_name='parkingconfiguration',
            name='tenant_allowance_enabled',
            field=models.BooleanField(default=True, help_text='When on, registered tenant vehicles park free only up to the allowance below; time past it is billed normally. When off, pass holders park free without limit and other tenants are billed like visitors.'),
        ),
        migrations.AddField(
            model_name='parkingconfiguration',
            name='tenant_free_hours',
            field=models.PositiveSmallIntegerField(default=12, help_text='Free parking hours per vehicle within the lookback period.'),
        ),
        migrations.AddField(
            model_name='parkingconfiguration',
            name='tenant_lookback_hours',
            field=models.PositiveSmallIntegerField(default=24, help_text="Rolling period the free hours are counted over. Earlier sessions in this period use up the allowance, so re-entering doesn't reset it."),
        ),
    ]
