# Generated by Django 5.2.2 on 2026-09-24 10:42

import datetime
from decimal import Decimal
from django.db import migrations, models

NIGHT_RATE_BY_CATEGORY = {'CAR': Decimal('100.00'), 'BIKE': Decimal('50.00')}


def seed_night_rates(apps, schema_editor):
    """100/h on plans used by cars, 50/h on plans used by bikes. A plan
    shared by both categories is left at 0 for an admin to set by hand."""
    PricingPlan = apps.get_model('management', 'PricingPlan')
    VehicleType = apps.get_model('management', 'VehicleType')
    for plan in PricingPlan.objects.all():
        categories = set(VehicleType.objects.filter(pricing_plan=plan)
                         .values_list('category', flat=True))
        if len(categories) != 1:
            if len(categories) > 1:
                print(f"\n  Skipped night rate for shared plan '{plan.name}' — set it by hand.")
            continue
        rate = NIGHT_RATE_BY_CATEGORY.get(categories.pop())
        if rate is not None:
            plan.night_rate_per_hour = rate
            plan.save(update_fields=['night_rate_per_hour'])


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_tenant_12h_allowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingconfiguration',
            name='night_end',
            field=models.TimeField(default=datetime.time(6, 0)),
        ),
        migrations.AddField(
            model_name='parkingconfiguration',
            name='night_pricing_enabled',
            field=models.BooleanField(default=True, help_text="When on, time parked inside the night window is billed at each pricing plan's night rate."),
        ),
        migrations.AddField(
            model_name='parkingconfiguration',
            name='night_start',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='night_rate_per_hour',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Hourly rate for time inside the night window (ParkingConfiguration). 0 means night time is billed like day time.', max_digits=8),
        ),
        migrations.RunPython(seed_night_rates, migrations.RunPython.noop),
    ]
