# Generated by Django 5.2.2 on 2026-09-28 08:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_disable_tenant_allowance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingconfiguration',
            name='student_free_minutes',
            field=models.PositiveIntegerField(default=150, help_text='Free minutes per visit for an approved, active student within their batch dates.'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=20, verbose_name='S.N.')),
                ('name', models.CharField(max_length=150)),
                ('contact_number', models.CharField(blank=True, max_length=30)),
                ('license_plate', models.CharField(db_index=True, max_length=20, verbose_name='Vehicle number')),
                ('batch_start_date', models.DateField(blank=True, null=True)),
                ('batch_end_date', models.DateField(help_text='Last day the student parks free. The student stops matching at the gate after this.')),
                ('class_days', models.JSONField(blank=True, default=list, help_text='e.g. ["SUN", "MON"]')),
                ('class_time_from', models.TimeField(blank=True, null=True)),
                ('class_time_to', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive students are billed like visitors.')),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=255)),
                ('card_code', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.vehicletype')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='management.vendor')),
            ],
            options={
                'verbose_name': 'Student',
                'ordering': ['request_id', 'id'],
            },
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='student',
            field=models.ForeignKey(blank=True, editable=False, help_text='Approved student matched by vehicle number or student card; gets ParkingConfiguration.student_free_minutes free per visit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='management.student'),
        ),
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual entry'), ('CSV', 'CSV file'), ('EXCEL', 'Excel file')], default='MANUAL', max_length=10)),
                ('original_file', models.FileField(blank=True, null=True, upload_to='student_requests/')),
                ('note', models.TextField(blank=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_requests', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_requests', to='management.vendor')),
            ],
            options={
                'verbose_name': 'Student Request',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='management.studentrequest'),
        ),
    ]
