# Generated by Django 5.2.2 on 2026-09-29 17:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_enable_tenant_allowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingconfiguration',
            name='lost_ticket_fine',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Charged in place of the parking fee when a customer loses their ticket.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='lost_ticket',
            field=models.BooleanField(default=False, editable=False, help_text='Closed at the POS as a lost ticket: charged the flat ParkingConfiguration.lost_ticket_fine instead of the parking fee.'),
        ),
    ]
