# Generated by Django 5.2.2 on 2026-09-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_student_class_window'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingconfiguration',
            name='student_free_minutes',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='student_free_minutes',
        ),
        migrations.AddField(
            model_name='parkingconfiguration',
            name='student_late_grace_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Default free minutes after class end (leaving late), for tenants without their own Vendor.student_late_grace_minutes.'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='student_early_grace_minutes',
            field=models.PositiveIntegerField(blank=True, help_text="Free minutes before class start for this tenant's students. Blank uses the global default (Parking Configuration).", null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='student_late_grace_minutes',
            field=models.PositiveIntegerField(blank=True, help_text="Free minutes after class end for this tenant's students. Blank uses the global default (Parking Configuration).", null=True),
        ),
        migrations.AlterField(
            model_name='parkingconfiguration',
            name='student_early_grace_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Default free minutes before class start (arriving early), for tenants without their own Vendor.student_early_grace_minutes.'),
        ),
    ]
