# Generated by Django 5.2.2 on 2026-09-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_student_grace_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingconfiguration',
            name='night_evening_grace_minutes',
            field=models.PositiveIntegerField(default=15, help_text="Registered vehicles leaving this many minutes or less after night start (e.g. 22:15 for a 22:00 start) aren't charged for those night minutes."),
        ),
        migrations.AddField(
            model_name='parkingconfiguration',
            name='night_morning_grace_minutes',
            field=models.PositiveIntegerField(default=15, help_text="Registered vehicles arriving this many minutes or less before night end (e.g. 05:45 for a 06:00 end) aren't charged for those night minutes."),
        ),
    ]
