# Generated by Django 5.1.15 on 2026-10-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_night_boundary_grace'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='tenant_free_hours',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Hours from entry that this tenant's registered vehicles park free (day hours only). Blank uses the global default (Parking Configuration).", null=True),
        ),
    ]
