# Generated by Django 5.1.15 on 2026-10-02 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_vendor_tenant_free_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsession',
            name='entry_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
