# Generated by Django 5.2.2 on 2026-10-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_parkingsession_entry_time_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='parkingsession',
            index=models.Index(fields=['status', '-entry_time'], name='session_status_entry_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingsession',
            index=models.Index(fields=['exit_time'], name='session_exit_time_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingsession',
            index=models.Index(fields=['registered_staff_member', 'entry_time'], name='session_staff_entry_idx'),
        ),
    ]
