# Template for backend/parkingcore/local_settings.py.
# Copy to local_settings.py and edit -- the real file is gitignored.
# On production this file is generated by CI from GitHub Secrets
# (.github/scripts/gen_local_settings.py), so do not expect them to match.

DEBUG = True
ENVIRONMENT = 'development'
ALLOWED_HOSTS = ['*']

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'parking',
        'USER': 'postgres',
        'PASSWORD': 'your-local-postgres-password',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Point at your local EasyManage instance.
EASYMANAGE_API_BASE_URL = 'http://127.0.0.1:3000/api/integrations/parking'

# Fill these in from your local EasyManage .env when you need to exercise the
# integration endpoints; leave as-is otherwise (they fail closed).
PARKING_WEBHOOK_SECRET = None
EASYMANAGE_INTEGRATION_API_KEY = None
PARKING_READ_API_KEY = None
