# parking_management/models.py

import math
import uuid
import hmac
import hashlib
import struct
import time
from decimal import Decimal
import qrcode
import io
import base64
from django.urls import reverse

from django.core.exceptions import ValidationError
from django.db import models, transaction
from django.db.models import F, Sum
from django.utils import timezone

# --- Foundational Models ---


class ParkingConfiguration(models.Model):
    id = models.PositiveSmallIntegerField(
        primary_key=True, default=1, editable=False)
    currency_symbol = models.CharField(max_length=5, default='NRs')
    company_name = models.CharField(
        max_length=100, blank=True, default="Django Parking Inc.")

    def __str__(self): return "Parking System Global Configuration"
    def save(self, *args, **kwargs): self.pk = 1; super().save(*args, **kwargs)

    @classmethod
    def get_solo(cls): obj, created = cls.objects.get_or_create(
        pk=1); return obj

    class Meta:
        verbose_name = "Parking System Configuration"


class PricingPlan(models.Model):
    PLAN_TYPE_CHOICES = [('HOURLY', 'Hourly Rate'), ('FLAT_RATE_PER_DAY',
                                                     'Flat Rate Per Day'), ('TIERED_HOURLY', 'Tiered Hourly Blocks')]
    name = models.CharField(max_length=100, unique=True)
    plan_type = models.CharField(
        max_length=20, choices=PLAN_TYPE_CHOICES, default='HOURLY')
    rate_details = models.JSONField(default=dict)

    # NEW: Field for minimum charge
    minimum_charge = models.DecimalField(
        max_digits=6, decimal_places=2, default=Decimal('0.00'),
        help_text="The minimum fee for this plan, if the calculated charge is > 0. Set to 0 for no minimum."
    )
    is_sample = models.BooleanField(
        default=False, db_index=True,
        help_text="True if this record was generated by seed_parking_data. Never set manually."
    )

    def __str__(self): return f"{self.name} (Min: {self.minimum_charge})"

    class Meta:
        verbose_name = "Pricing Plan"
        verbose_name_plural = "Pricing Plans"


class VehicleType(models.Model):
    CATEGORY_CHOICES = [('CAR', 'Car'), ('BIKE', 'Bike')]

    name = models.CharField(max_length=50, unique=True)
    pricing_plan = models.ForeignKey(
        PricingPlan, on_delete=models.PROTECT, null=True)
    free_duration_minutes = models.PositiveIntegerField(default=5)
    # Drives quota enforcement against Vendor.car_quota/bike_quota — see
    # StaffSerializer.validate(). Only two categories exist today; extend
    # later if a third (e.g. e-bike) appears.
    category = models.CharField(
        max_length=10, choices=CATEGORY_CHOICES, default='CAR')
    is_sample = models.BooleanField(
        default=False, db_index=True,
        help_text="True if this record was generated by seed_parking_data. Never set manually."
    )

    def __str__(self):
        # return f"{self.name} (Free: {self.free_duration_minutes}min)"
        return f"{self.name}"

    class Meta:
        verbose_name = "Vehicle Type"
        ordering = ['name']


class Vendor(models.Model):
    SYNC_SOURCE_CHOICES = [
        ('webhook', 'Webhook'),
        ('pull', 'Pull Reconcile'),
        ('manual', 'Manual'),
    ]

    name = models.CharField(max_length=150, unique=True)
    location = models.CharField(max_length=200, blank=True)
    contact_person = models.CharField(max_length=100, blank=True)
    contact_email = models.EmailField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_sample = models.BooleanField(
        default=False, db_index=True,
        help_text="True if this record was generated by seed_parking_data. Never set manually."
    )

    # --- EasyManage sync cache (Sallyan House gate integration) ---
    # EasyManage is the source of truth for these fields; Django only caches
    # them so the gate scanner never depends on a live call. Updated via
    # webhook (sync_vendor_from_payload) or the nightly reconcile_parking_tenants
    # command — never derived locally.
    external_tenant_id = models.CharField(
        max_length=64, unique=True, null=True, blank=True, db_index=True)
    car_quota = models.PositiveIntegerField(default=0)
    bike_quota = models.PositiveIntegerField(default=0)
    gate_access_allowed = models.BooleanField(default=True)
    last_synced_at = models.DateTimeField(null=True, blank=True)
    sync_source = models.CharField(
        max_length=20, choices=SYNC_SOURCE_CHOICES, null=True, blank=True)

    # --- Ticket stamping ---
    # A tenant physically stamps a visitor's parking chit; the gate operator
    # records that stamp against the visitor's ParkingSession (see
    # TicketStamp / ParkingSession.add_stamp) instead of waving them through
    # as a cash payment. This is how many free minutes each stamp is worth.
    stamp_free_minutes = models.PositiveIntegerField(
        default=60,
        help_text="Free parking minutes granted each time this tenant stamps a visitor's ticket."
    )

    def __str__(self): return self.name

    class Meta:
        verbose_name = "Vendor / Tenant"
        ordering = ['name']


class Staff(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(null=True, blank=True)
    company = models.ForeignKey(
        Vendor, on_delete=models.SET_NULL, null=True, blank=True)
    license_plate = models.CharField(max_length=20, unique=True, db_index=True)
    vehicle_type = models.ForeignKey(
        VehicleType, on_delete=models.SET_NULL, null=True, blank=True)
    card_code = models.UUIDField(
        default=uuid.uuid4, editable=False, unique=True, db_index=True,
        help_text="Encoded on the tenant's permanent physical parking card (QR/barcode). "
                   "Never rotates — regenerate via admin action if the physical card is lost."
    )
    is_card_active = models.BooleanField(
        default=True,
        help_text="Uncheck to instantly block this card at the gate (lost/leaked) without losing history."
    )
    card_issued_at = models.DateTimeField(default=timezone.now)
    is_sample = models.BooleanField(
        default=False, db_index=True,
        help_text="True if this record was generated by seed_parking_data. Never set manually."
    )

    DIGITAL_TOKEN_SALT = 'tenant-card-digital'
    DIGITAL_TOKEN_MAX_AGE = 60  # seconds a digital QR stays valid before the app must refresh it

    @staticmethod
    def _qr_base64(data):
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=4,
        )
        qr.add_data(data)
        qr.make(fit=True)
        img = qr.make_image(fill_color="black", back_color="white")
        buffer = io.BytesIO()
        img.save(buffer, format="PNG")
        return base64.b64encode(buffer.getvalue()).decode()

    def generate_card_qr_code(self):
        """Static QR for the permanent physical card — encodes the raw card_code."""
        return self._qr_base64(str(self.card_code))

    def generate_digital_token(self):
        """Short-lived signed token for the digital card view. Expires in
        DIGITAL_TOKEN_MAX_AGE seconds, so a screenshot goes stale fast."""
        from django.core.signing import TimestampSigner
        signer = TimestampSigner(salt=self.DIGITAL_TOKEN_SALT)
        return signer.sign(str(self.card_code))

    def generate_digital_qr_code(self):
        return self._qr_base64(self.generate_digital_token())

    # --- Offline mode: TOTP-style rotating code, verifiable with zero network
    # calls at scan time. Trade-off vs. the online token: the per-card secret
    # is delivered to the client once (at page load) so it can keep computing
    # fresh codes with no connectivity — meaning anyone who extracts that
    # secret from the page can also generate future codes offline. Only use
    # this path when the tenant genuinely has no signal at the gate; the
    # online signed-token mode above is strictly more secure and should stay
    # the default whenever a network call is possible.
    OFFLINE_SECRET_SALT = 'tenant-card-offline'
    OFFLINE_TOTP_STEP_SECONDS = 30
    OFFLINE_TOTP_DIGITS = 6
    OFFLINE_TOTP_DRIFT_STEPS = 2  # tolerate up to ~1 min of clock drift/scan delay either side

    def _offline_secret_bytes(self):
        from django.conf import settings
        msg = f"{self.OFFLINE_SECRET_SALT}:{self.card_code}".encode()
        return hmac.new(settings.SECRET_KEY.encode(), msg, hashlib.sha256).digest()

    def offline_secret_hex(self):
        """Delivered to the client once so it can compute rotating codes offline."""
        return self._offline_secret_bytes().hex()

    @classmethod
    def _totp_at_step(cls, secret_bytes, step):
        msg = struct.pack('>Q', step)
        digest = hmac.new(secret_bytes, msg, hashlib.sha1).digest()
        offset = digest[-1] & 0x0F
        code_int = (struct.unpack('>I', digest[offset:offset + 4])[0] & 0x7FFFFFFF) % (10 ** cls.OFFLINE_TOTP_DIGITS)
        return str(code_int).zfill(cls.OFFLINE_TOTP_DIGITS)

    def current_offline_code(self):
        step = int(time.time() // self.OFFLINE_TOTP_STEP_SECONDS)
        return self._totp_at_step(self._offline_secret_bytes(), step)

    def generate_offline_qr_payload(self):
        return f"{self.card_code}#{self.current_offline_code()}"

    def generate_offline_qr_code(self):
        return self._qr_base64(self.generate_offline_qr_payload())

    def verify_offline_code(self, code):
        secret = self._offline_secret_bytes()
        current_step = int(time.time() // self.OFFLINE_TOTP_STEP_SECONDS)
        return any(
            self._totp_at_step(secret, current_step + drift) == code
            for drift in range(-self.OFFLINE_TOTP_DRIFT_STEPS, self.OFFLINE_TOTP_DRIFT_STEPS + 1)
        )

    @classmethod
    def resolve_scanned_code(cls, raw_value):
        """
        Accepts a raw card_code UUID (physical card), a signed digital token
        (online digital card), or a "<card_code>#<totp>" offline code.
        Returns the underlying card_code string, or None if invalid/expired.
        """
        from django.core.signing import BadSignature, SignatureExpired, TimestampSigner

        if '#' in raw_value:
            card_code_str, _, code = raw_value.partition('#')
            try:
                staff = cls.objects.get(card_code=card_code_str)
            except (cls.DoesNotExist, ValueError, ValidationError):
                return None
            return card_code_str if staff.verify_offline_code(code) else None

        if ':' in raw_value:
            signer = TimestampSigner(salt=cls.DIGITAL_TOKEN_SALT)
            try:
                return signer.unsign(raw_value, max_age=cls.DIGITAL_TOKEN_MAX_AGE)
            except (BadSignature, SignatureExpired):
                return None

        return raw_value

    def __str__(self): return f"{self.name} - {self.license_plate}"

    class Meta:
        verbose_name = "Tenant Member"
        verbose_name_plural = "Tenant Members"
        ordering = ['name']


class Coupon(models.Model):
    VALIDATION_TYPE_CHOICES = [
        ('FREE_MINUTES', 'Grant Free Minutes'), ('COMPLETE_WAIVER', 'Waive Entire Session')]
    code = models.CharField(max_length=30, unique=True, db_index=True)
    validation_type = models.CharField(
        max_length=20, choices=VALIDATION_TYPE_CHOICES)
    value_minutes = models.PositiveIntegerField(default=0)
    issued_by = models.ForeignKey(
        Vendor, on_delete=models.SET_NULL, null=True, blank=True)
    price = models.DecimalField(
        max_digits=6, decimal_places=2, default=Decimal('0.00'))
    is_active = models.BooleanField(default=True)
    valid_from = models.DateTimeField(null=True, blank=True)
    valid_until = models.DateTimeField(null=True, blank=True)
    max_uses = models.PositiveIntegerField(default=1)
    times_used = models.PositiveIntegerField(default=0, editable=False)

    batch = models.ForeignKey(
        'CouponBatch',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="coupons",
        help_text="The batch this coupon was generated from, if any."
    )
    is_sample = models.BooleanField(
        default=False, db_index=True,
        help_text="True if this record was generated by seed_parking_data. Never set manually."
    )

    def is_valid(self):
        if not self.is_active:
            return False, "Coupon is not active."
        now = timezone.now()
        if self.valid_from and self.valid_from > now:
            return False, "Coupon is not yet valid."
        if self.valid_until and self.valid_until < now:
            return False, "Coupon has expired."
        if self.max_uses is not None and self.times_used >= self.max_uses:
            return False, "Coupon has been used to its limit."
        return True, "Coupon is valid."

    def __str__(
            self):
        return f"Coupon {self.code} ({self.get_validation_type_display()})"

    class Meta:
        verbose_name = "Parking Coupon"
        verbose_name_plural = "Parking Coupons"


class CouponBatch(models.Model):
    """
    Represents a bulk purchase of coupons by a vendor.
    Creating or saving this model will generate the individual Coupon objects.
    """
    PAYMENT_METHOD_CHOICES = [
        ('CASH', 'Cash'), ('ONLINE_PAYMENT', 'Online Payment')]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    vendor = models.ForeignKey(Vendor, on_delete=models.PROTECT, related_name="coupon_batches")
    purchase_date = models.DateTimeField(default=timezone.now)

    # --- Coupon Template Details ---
    # These fields define what kind of coupons will be generated.
    validation_type = models.CharField(max_length=20, choices=Coupon.VALIDATION_TYPE_CHOICES)
    value_minutes = models.PositiveIntegerField(default=0, help_text="For 'Grant Free Minutes' coupons.")
    valid_from = models.DateTimeField(null=True, blank=True)
    valid_until = models.DateTimeField(null=True, blank=True)

    # --- Purchase Details ---
    number_of_coupons = models.PositiveIntegerField(default=10)
    base_price_per_coupon = models.DecimalField(max_digits=6, decimal_places=2, default=Decimal('0.00'))
    total_price = models.DecimalField(max_digits=10, decimal_places=2, editable=False)
    is_paid = models.BooleanField(default=False)
    payment_method = models.CharField(max_length=20, choices=PAYMENT_METHOD_CHOICES, null=True, blank=True)
    notes = models.TextField(blank=True, help_text="Internal notes about this batch purchase.")
    is_sample = models.BooleanField(
        default=False, db_index=True,
        help_text="True if this record was generated by seed_parking_data. Never set manually."
    )

    def __str__(self):
        return f"{self.vendor.name} ({self.number_of_coupons} coupons) on {self.purchase_date.strftime('%Y-%m-%d')}"

    def clean(self):
        # Calculate total price before validation
        self.total_price = self.base_price_per_coupon * self.number_of_coupons
        if self.is_paid and not self.payment_method:
            raise ValidationError("A payment method is required if the batch is marked as paid.")

    def save(self, *args, **kwargs):
        self.full_clean()  # Run validation and calculate total price

        # Check if this is a new, unsaved batch
        is_new = self._state.adding

        super().save(*args, **kwargs)  # Save the batch first to get a PK

        if is_new:
            # Use a transaction to ensure all coupons are created or none are.
            with transaction.atomic():
                coupons_to_create = []
                for i in range(self.number_of_coupons):
                    # Generate a unique, predictable code
                    # Format: BATCH-<BatchID_short>-<sequence>
                    code_sequence = str(i + 1).zfill(len(str(self.number_of_coupons)))
                    unique_code = f"B-{str(self.id)[:8].upper()}-{code_sequence}"

                    coupons_to_create.append(
                        Coupon(
                            batch=self,  # Link back to this batch
                            code=unique_code,
                            validation_type=self.validation_type,
                            value_minutes=self.value_minutes,
                            issued_by=self.vendor,
                            price=self.base_price_per_coupon,
                            is_active=True,  # New coupons are active by default
                            valid_from=self.valid_from,
                            valid_until=self.valid_until,
                            max_uses=1  # Typically one use per printed coupon
                        )
                    )
                Coupon.objects.bulk_create(coupons_to_create)

    class Meta:
        verbose_name = "Coupon Batch Purchase"
        verbose_name_plural = "Coupon Batch Purchases"
        ordering = ['-purchase_date']

class ParkingPass(models.Model):
    staff = models.ForeignKey(
        Staff, on_delete=models.CASCADE, related_name="parking_passes")
    valid_from = models.DateTimeField()
    valid_until = models.DateTimeField()
    price_paid = models.DecimalField(
        max_digits=8, decimal_places=2, default=Decimal('0.00'))
    is_active = models.BooleanField(default=True)
    notes = models.TextField(blank=True)
    is_sample = models.BooleanField(
        default=False, db_index=True,
        help_text="True if this record was generated by seed_parking_data. Never set manually."
    )

    def is_valid_at(
            self, check_datetime): return self.is_active and self.valid_from <= check_datetime <= self.valid_until

    def generate_qr_code(self):
        # Create QR code data - includes staff ID and license plate
        qr_data = f"staff_id:{self.staff.id};license_plate:{self.staff.license_plate}"

        # Generate QR code
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=4,
        )
        qr.add_data(qr_data)
        qr.make(fit=True)

        # Create image
        img = qr.make_image(fill_color="black", back_color="white")

        # Convert to base64 for embedding in HTML
        buffer = io.BytesIO()
        img.save(buffer, format="PNG")
        return base64.b64encode(buffer.getvalue()).decode()

    def __str__(
            self): return f"Pass for {self.staff.name} (until {self.valid_until.strftime('%Y-%m-%d')})"

    class Meta:
        verbose_name = "Subscription Pass"
        verbose_name_plural = "Subscription Passes"
        ordering = ['-valid_until']


class ParkingSession(models.Model):
    # ... (Field definitions are correct) ...
    SESSION_STATUS_CHOICES = [('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), (
        'PAID', 'Paid'), ('WAIVED', 'Waived'), ('COVERED_BY_PASS', 'Covered by Pass'),
        ('STAMPED', 'Stamped')]
    PAYMENT_METHOD_CHOICES = [
        ('CASH', 'Cash'), ('ONLINE_PAYMENT', 'Online Payment')]
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    # <<< KEY FIELD DEFINITION >>>
    ticket_number = models.CharField(
        max_length=30,  # Increased length for safety
        unique=True,  # This is correct and necessary
        blank=True,  # Allows the field to be blank before we generate the value
        editable=False  # Hides it from forms (like the Admin)
    )

    vehicle_type = models.ForeignKey('VehicleType', on_delete=models.PROTECT)
    license_plate = models.CharField(
        max_length=20, db_index=True, blank=True, null=True)
    registered_staff_member = models.ForeignKey(
        'Staff', on_delete=models.SET_NULL, null=True, blank=True, related_name='parking_sessions', editable=False)
    entry_time = models.DateTimeField(default=timezone.now)
    exit_time = models.DateTimeField(null=True, blank=True)
    duration_minutes = models.PositiveIntegerField(
        null=True, blank=True, editable=False)
    applied_coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, null=True, blank=True)
    applied_pass = models.ForeignKey(
        'ParkingPass', on_delete=models.SET_NULL, null=True, blank=True, editable=False)
    calculated_charge = models.DecimalField(
        max_digits=8, decimal_places=2, null=True, blank=True)
    payment_method = models.CharField(
        max_length=20, choices=PAYMENT_METHOD_CHOICES, null=True, blank=True)
    status = models.CharField(
        max_length=20, choices=SESSION_STATUS_CHOICES, default='ACTIVE', db_index=True)
    notes = models.TextField(blank=True)
    is_sample = models.BooleanField(
        default=False, db_index=True,
        help_text="True if this record was generated by seed_parking_data. Never set manually."
    )

    class Meta:
        ordering = ['-entry_time']
        verbose_name = "Parking Session"

    def __str__(self):
        return f"Ticket #{self.ticket_number or 'N/A'} ({self.license_plate or 'No Plate'}) - {self.get_status_display()}"

    def _generate_ticket_number(self):
        # This logic is correct.
        today = timezone.now().date()
        today_str = today.strftime('%Y%m%d')
        prefix = f"TI{today_str}"
        last_ticket = ParkingSession.objects.filter(ticket_number__startswith=prefix).order_by('ticket_number').last()

        if not last_ticket:
            next_seq = 1
        else:
            try:
                last_seq_str = last_ticket.ticket_number.split('-')[-1]
                next_seq = int(last_seq_str) + 1
            except (ValueError, IndexError):
                count = ParkingSession.objects.filter(ticket_number__startswith=prefix).count()
                next_seq = count + 1

        return f"{prefix}-{str(next_seq).zfill(5)}"

    # <<< KEY METHOD >>>
    def save(self, *args, **kwargs):
        # Generate ticket number if it doesn't exist
        if not self.ticket_number:
            self.ticket_number = self._generate_ticket_number()

        # Rest of your save logic...
        if self.license_plate and not self.registered_staff_member_id:
            staff_obj = Staff.objects.filter(license_plate__iexact=self.license_plate).first()
            if staff_obj:
                self.registered_staff_member = staff_obj

        super().save(*args, **kwargs)

    def _round_charge_up_to_multiple(self, amount, multiple=Decimal('5')):
        if amount <= 0:
            return Decimal('0.00')
        return (Decimal(math.ceil(amount / multiple)) * multiple).quantize(Decimal('0.01'))

    def calculate_total_duration_minutes(self):
        effective_exit_time = self.exit_time or timezone.now()
        if self.entry_time > effective_exit_time:
            return 0
        return int((effective_exit_time - self.entry_time).total_seconds() / 60)

    def update_and_calculate_charges(self):
        if self.status in ['PAID', 'COVERED_BY_PASS'] or not self.exit_time:
            return

        # Calculate duration if not set
        if not self.duration_minutes:
            self.duration_minutes = self.calculate_total_duration_minutes()

        # Check for staff pass
        if self.registered_staff_member:
            active_pass = self.registered_staff_member.parking_passes.filter(
                is_active=True,
                valid_from__lte=self.exit_time,
                valid_until__gte=self.exit_time
            ).first()
            if active_pass:
                self.applied_pass = active_pass
                self.calculated_charge = Decimal('0.00')
                self.status = 'COVERED_BY_PASS'
                return

        # A tenant stamp fully supersedes visitor billing — see
        # refresh_stamp_coverage — so a stamped ticket never reaches the
        # normal charge calculation below.
        if self.refresh_stamp_coverage():
            return

        # Calculate free minutes
        free_minutes = self.vehicle_type.free_duration_minutes

        # Add coupon minutes if applicable
        if self.applied_coupon and self.applied_coupon.validation_type == 'FREE_MINUTES':
            free_minutes += self.applied_coupon.value_minutes

        # Calculate chargeable minutes
        chargeable_minutes = max(0, self.duration_minutes - free_minutes)

        # Calculate base charge
        subtotal = self._calculate_charge_from_plan(chargeable_minutes)

        # Apply minimum charge only if there are chargeable minutes
        if chargeable_minutes > 0:
            pricing_plan = self.vehicle_type.pricing_plan
            if pricing_plan and pricing_plan.minimum_charge > 0 and subtotal < pricing_plan.minimum_charge:
                subtotal = pricing_plan.minimum_charge

        # Set final charge and status
        self.calculated_charge = self._round_charge_up_to_multiple(subtotal)
        self.status = 'WAIVED' if self.calculated_charge == Decimal('0.00') else 'COMPLETED'

    def apply_coupon(self, coupon_code):
        if self.status not in ['ACTIVE', 'COMPLETED']:
            raise ValidationError("Cannot apply coupon to a completed or paid session")

        coupon = Coupon.objects.get(code__iexact=coupon_code)
        is_valid, message = coupon.is_valid()
        if not is_valid:
            raise ValidationError(message)

        if coupon.validation_type == 'FREE_MINUTES' and coupon.value_minutes <= 0:
            raise ValidationError("This coupon doesn't provide any free minutes")

        self.applied_coupon = coupon
        self.save()  # This will trigger charge recalculation

    @property
    def total_stamp_minutes(self):
        return self.stamps.aggregate(total=Sum('free_minutes_granted'))['total'] or 0

    def refresh_stamp_coverage(self):
        """
        A tenant stamp covers the visitor for free up to the sum of minutes
        granted by this ticket's stamps (Vendor.stamp_free_minutes at stamp
        time). While elapsed time stays within that window the session is
        fully "stamped" and the visitor is never charged. Once it overstays
        the window, the excess is billed to the tenant (the vendor of the
        most recent stamp) instead of the visitor — recorded on
        TenantBill — and the session falls back to its normal status.

        Called both while the session is still parked (stamp lookup/scan,
        since elapsed time keeps moving until exit) and at exit to
        finalize. Returns True if this session has stamps and was handled
        here (caller should skip normal charge calculation), False if there
        are no stamps to consider.
        """
        total_free = self.total_stamp_minutes
        if total_free <= 0:
            return False

        elapsed = self.duration_minutes if self.exit_time else self.calculate_total_duration_minutes()
        overage = elapsed - total_free

        if overage > 0:
            latest_stamp = self.stamps.order_by('-stamped_at').first()
            amount = self._round_charge_up_to_multiple(
                self._calculate_charge_from_plan(overage))
            TenantBill.objects.update_or_create(
                session=self,
                defaults={
                    'vendor': latest_stamp.vendor,
                    'overage_minutes': overage,
                    'amount': amount,
                },
            )
            self.status = 'COMPLETED' if self.exit_time else 'ACTIVE'
        else:
            TenantBill.objects.filter(session=self).delete()
            self.status = 'STAMPED'

        if self.exit_time:
            self.calculated_charge = Decimal('0.00')

        return True

    def add_stamp(self, vendor):
        if self.status not in ['ACTIVE', 'COMPLETED', 'STAMPED']:
            raise ValidationError("Cannot stamp a completed or paid session.")

        stamp = TicketStamp.objects.create(
            session=self, vendor=vendor, free_minutes_granted=vendor.stamp_free_minutes)

        # If `stamps` was already prefetched onto this instance (e.g. by the
        # viewset's queryset), that cache is now stale — drop it so
        # session.stamps.all() and total_stamp_minutes see the new row.
        getattr(self, '_prefetched_objects_cache', {}).pop('stamps', None)

        self.refresh_stamp_coverage()
        self.save()

        return stamp

    def mark_as_paid(self, method=None):
        if self.applied_coupon:
            Coupon.objects.filter(pk=self.applied_coupon.pk).update(
                times_used=F('times_used') + 1)
        self.status = 'PAID'
        self.payment_method = method
        if method:
            self.notes += f"\nPaid via {self.get_payment_method_display()}."

    @property
    def undiscounted_charge(self):
        if self.duration_minutes is None:
            if self.exit_time:
                self.duration_minutes = self.calculate_total_duration_minutes()
            else:
                return Decimal('0.00')
        return self._calculate_charge_from_plan(self.duration_minutes).quantize(Decimal('0.01'))

    @property
    def charge_after_discount(self):
        if self.status == 'ACTIVE' or not self.exit_time:
            return Decimal('0.00')

        # Ensure duration_minutes is calculated if it's None
        if self.duration_minutes is None:
            self.duration_minutes = self.calculate_total_duration_minutes()

        free_minutes_grace = self.vehicle_type.free_duration_minutes
        free_minutes_coupon = self.applied_coupon.value_minutes if (
                self.applied_coupon and self.applied_coupon.validation_type == 'FREE_MINUTES') else 0
        free_minutes_stamps = self.total_stamp_minutes
        chargeable_minutes = max(
            0, self.duration_minutes - (free_minutes_grace + free_minutes_coupon + free_minutes_stamps))
        return self._calculate_charge_from_plan(chargeable_minutes).quantize(Decimal('0.01'))

    @property
    def discount_value(self):
        return max(Decimal('0.00'), self.undiscounted_charge - self.charge_after_discount)

    def _calculate_charge_from_plan(self, chargeable_minutes: int) -> Decimal:
        """
        Calculates the raw charge based on the vehicle's pricing plan
        and a given number of chargeable minutes. This is the core billing logic.
        """
        if chargeable_minutes <= 0:
            return Decimal('0.00')

        plan = self.vehicle_type.pricing_plan
        if not plan:
            # Fallback if no pricing plan is assigned to the vehicle type
            return Decimal('0.00')

        # --- HOURLY (FIXED) ---
        if plan.plan_type == 'HOURLY':
            # Example rate_details: {"rate_per_hour": "50.00"}
            rate_per_hour = Decimal(str(plan.rate_details.get('rate_per_hour', '0.00')))
            if rate_per_hour <= 0:
                return Decimal('0.00')

            # FIXED: Calculate proportional charge based on actual minutes
            # Instead of charging for full hours only, charge proportionally
            total_hours = Decimal(chargeable_minutes) / Decimal('60')
            return (total_hours * rate_per_hour).quantize(Decimal('0.01'))

        # --- FLAT_RATE_PER_DAY ---
        elif plan.plan_type == 'FLAT_RATE_PER_DAY':
            # Example rate_details: {"rate_per_day": "300.00"}
            rate_per_day = Decimal(str(plan.rate_details.get('rate_per_day', '0.00')))
            if rate_per_day <= 0:
                return Decimal('0.00')
            # A "day" is a 24-hour period from entry.
            days = Decimal(math.ceil(Decimal(chargeable_minutes) / (Decimal('60') * Decimal('24'))))
            return (days * rate_per_day).quantize(Decimal('0.01'))

        # --- TIERED_HOURLY ---
        elif plan.plan_type == 'TIERED_HOURLY':
            # Example rate_details: {"tiers": [
            #   {"up_to_hours": 2, "rate": "40.00"},
            #   {"up_to_hours": 5, "rate": "30.00"},
            #   {"up_to_hours": 24, "rate": "20.00"}
            # ]}
            tiers = plan.rate_details.get('tiers', [])
            if not tiers:
                return Decimal('0.00')

            sorted_tiers = sorted(tiers, key=lambda x: x['up_to_hours'])

            total_charge = Decimal('0.00')
            minutes_remaining = chargeable_minutes
            previous_tier_hours = 0

            for tier in sorted_tiers:
                tier_limit_hours = Decimal(str(tier.get('up_to_hours', 0)))
                tier_rate_per_hour = Decimal(str(tier.get('rate', '0.00')))

                # Calculate how many hours are in this tier bracket
                tier_duration_hours = tier_limit_hours - previous_tier_hours
                if tier_duration_hours <= 0:
                    continue

                # Convert tier duration to minutes
                tier_duration_minutes = int(tier_duration_hours * 60)

                # Calculate minutes to charge in this tier
                minutes_in_this_tier = min(minutes_remaining, tier_duration_minutes)

                if minutes_in_this_tier > 0:
                    # FIXED: Proportional charging instead of ceiling
                    hours_in_this_tier = Decimal(minutes_in_this_tier) / Decimal('60')
                    tier_charge = hours_in_this_tier * tier_rate_per_hour
                    total_charge += tier_charge
                    minutes_remaining -= minutes_in_this_tier

                previous_tier_hours = tier_limit_hours
                if minutes_remaining <= 0:
                    break

            # Handle any remaining minutes beyond the highest tier
            if minutes_remaining > 0 and sorted_tiers:
                last_tier_rate = Decimal(str(sorted_tiers[-1].get('rate', '0.00')))
                remaining_hours = Decimal(minutes_remaining) / Decimal('60')
                total_charge += remaining_hours * last_tier_rate

            return total_charge.quantize(Decimal('0.01'))

        # Fallback for unknown plan types
        return Decimal('0.00')


class TicketStamp(models.Model):
    """
    Records a tenant's physical stamp on a visitor's parking chit. Each
    stamp grants free minutes toward the visitor's ParkingSession (see
    ParkingSession.add_stamp/total_stamp_minutes) so the gate operator has
    a real audit trail for the visit instead of recording it as a cash
    payment that was never actually taken.
    """
    session = models.ForeignKey(
        ParkingSession, on_delete=models.CASCADE, related_name='stamps')
    vendor = models.ForeignKey(
        Vendor, on_delete=models.PROTECT, related_name='ticket_stamps')
    free_minutes_granted = models.PositiveIntegerField(
        help_text="Snapshot of the tenant's stamp_free_minutes at the time this stamp was recorded."
    )
    stamped_at = models.DateTimeField(default=timezone.now)
    is_sample = models.BooleanField(
        default=False, db_index=True,
        help_text="True if this record was generated by seed_parking_data. Never set manually."
    )

    def __str__(self):
        return f"{self.vendor.name} stamp on {self.session.ticket_number}"

    class Meta:
        verbose_name = "Ticket Stamp"
        verbose_name_plural = "Ticket Stamps"
        ordering = ['-stamped_at']


class TenantBill(models.Model):
    """
    Tracks the parking charge for time a visitor's stamped ticket ran past
    the total free minutes granted by its stamps (see
    ParkingSession.refresh_stamp_coverage). A stamped ticket's visitor is
    never charged at the gate — if they overstay what the tenant covered,
    the excess is billed to the tenant instead, recorded here for now
    rather than routed through any real tenant invoicing flow.
    """
    session = models.OneToOneField(
        ParkingSession, on_delete=models.CASCADE, related_name='tenant_bill')
    vendor = models.ForeignKey(
        Vendor, on_delete=models.PROTECT, related_name='tenant_bills')
    overage_minutes = models.PositiveIntegerField(
        help_text="Minutes parked beyond the total free minutes granted by this ticket's stamps."
    )
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_sample = models.BooleanField(
        default=False, db_index=True,
        help_text="True if this record was generated by seed_parking_data. Never set manually."
    )

    def __str__(self):
        return f"{self.vendor.name} bill for {self.session.ticket_number} ({self.overage_minutes}min over)"

    class Meta:
        verbose_name = "Tenant Bill"
        verbose_name_plural = "Tenant Bills"
        ordering = ['-created_at']


class CardScanLog(models.Model):
    SOURCE_CHOICES = [
        ('PHYSICAL', 'Physical Card'),
        ('DIGITAL', 'Digital Card (Online)'),
        ('OFFLINE', 'Digital Card (Offline)'),
    ]
    ACTION_CHOICES = [('ENTRY', 'Entry'), ('EXIT', 'Exit'), ('REJECTED', 'Rejected')]

    staff = models.ForeignKey(
        Staff, on_delete=models.CASCADE, related_name='scan_logs', null=True, blank=True)
    card_code_used = models.CharField(max_length=64, blank=True)
    action = models.CharField(max_length=10, choices=ACTION_CHOICES)
    source = models.CharField(max_length=10, choices=SOURCE_CHOICES, default='PHYSICAL')
    reject_reason = models.CharField(max_length=100, blank=True)
    scanned_at = models.DateTimeField(auto_now_add=True, db_index=True)
    is_sample = models.BooleanField(
        default=False, db_index=True,
        help_text="True if this record was generated by seed_parking_data. Never set manually."
    )

    def __str__(self):
        who = self.staff.name if self.staff else 'unknown'
        return f"{who} - {self.action} ({self.source}) @ {self.scanned_at:%Y-%m-%d %H:%M:%S}"

    class Meta:
        verbose_name = "Card Scan Log"
        verbose_name_plural = "Card Scan Logs"
        ordering = ['-scanned_at']


class WebhookEventLog(models.Model):
    """
    Dedup/audit log for inbound EasyManage webhook events. The receiver
    checks event_id first; if already seen, it returns 200 without
    reprocessing — makes retries (which will happen, per the outbox+cron
    design on the EasyManage side) safe no-ops.
    """
    STATUS_CHOICES = [
        ('received', 'Received'),
        ('processed', 'Processed'),
        ('failed', 'Failed'),
    ]

    event_id = models.CharField(max_length=64, unique=True, db_index=True)
    event_type = models.CharField(max_length=50)
    received_at = models.DateTimeField(auto_now_add=True)
    payload = models.JSONField(default=dict)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default='received')
    error = models.TextField(blank=True)

    def __str__(self):
        return f"{self.event_type} ({self.event_id}) - {self.status}"

    class Meta:
        verbose_name = "Webhook Event Log"
        verbose_name_plural = "Webhook Event Logs"
        ordering = ['-received_at']
