# Generated by Django 5.2.2 on 2026-09-28 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_student_requests'),
        ('user_app', '0002_seed_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Tenant-portal accounts only: the tenant this login belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_users', to='management.vendor'),
        ),
    ]
